In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

In [24]:
df = pd.read_csv("../data/student_scores.csv")

In [25]:
df.head()

   Hours_Studied  Test_Prep  Parent_Education  Exam_Score
0            3.5          0                 1          52
1            8.2          1                 3          89
2            5.1          0                 2          67
3            2.0          0                 1          41
4            7.5          1                 4          85

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Hours_Studied     15 non-null     float64
 1   Test_Prep         15 non-null     int64
 2   Parent_Education  15 non-null     int64
 3   Exam_Score        15 non-null     int64
dtypes: float64(1), int64(3)
memory usage: 612.0 bytes

In [27]:
df.describe()

       Hours_Studied  Test_Prep  Parent_Education  Exam_Score
count      15.000000  15.000000         15.000000    15.00000
mean        5.360000   0.400000          2.200000    67.80000
std         2.446222   0.507093          1.082326    18.59032
min         1.500000   0.000000          1.000000    35.00000
25%         3.300000   0.000000          1.000000    54.00000
50%         5.500000   0.000000          2.000000    70.00000
75%         7.250000   1.000000          3.000000    81.50000
max         9.000000   1.000000          4.000000    94.00000

In [28]:
df.isnull().sum()

Hours_Studied       0
Test_Prep           0
Parent_Education    0
Exam_Score          0
dtype: int64

In [29]:
X = df[['Hours_Studied', 'Test_Prep', 'Parent_Education']]
y = df['Exam_Score']

In [30]:
print(X.head())
print(y.head())

   Hours_Studied  Test_Prep  Parent_Education
0            3.5          0                 1
1            8.2          1                 3
2            5.1          0                 2
3            2.0          0                 1
4            7.5          1                 4
0    52
1    89
2    67
3    41
4    85
Name: Exam_Score, dtype: int64

In [31]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(12, 3)
(3, 3)

In [32]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [33]:
predictions = model.predict(X_test)

print(predictions[:10])

[70.30827846 93.73649229 52.0400202 ]

In [38]:
mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("MAE:", mae)
print("R2 Score:", r2)

MAE: 0.20393545636122212
R2 Score: 0.9998129802486734

In [40]:
joblib.dump(model, "students_score_prediction_model.pkl")

['students_score_prediction_model.pkl']

In [42]:
loaded_model = joblib.load("students_score_prediction_model.pkl")

In [46]:
sample = [[3, 0, 2]]

prediction = model.predict(sample)

print("Predicted Score:", prediction[0])

Predicted Score: 50.10167642900423

C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(